// src/components/Header.jsx
import React from "react";

function Header() {
  return (
    <div className="header-container">
      <h1>
        Anime{" "}
        <span
          style={{
            color: "red",
          }}
        >
          Quotes
        </span>
      </h1>
      <p>Click On The Button To Generate Random Anime Quote</p>
    </div>
  );
}

export default Header;

// src/lib/components/Header.svelte
<div class="header-container">
  <h1>
    Anime{" "}
    <span style="color: red;">Quotes</span>
  </h1>
  <p>Click On the Button To Generate Random Anime Quote</p>
</div>

<style>
  @import url("https://fonts.googleapis.com/css2?family=Bubblegum+Sans&display=swap");

  .header-container {
    overflow: auto;
    text-align: center;
  }

  .header-container h1 {
    margin-top: 10%;
    font-size: 2.5rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 7px;
    color: #fff;
    font-family: "Bubblegum Sans", cursive;
  }

  .header-container p {
    margin-top: 10px;
    font-size: 1.5rem;
    font-weight: 500;
    text-transform: uppercase;
    color: #fff;
    font-family: "Bubblegum Sans", cursive;
  }
</style>
